language: node_js
node_js:
- '10'
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: bisand/tibber-api
  tag: next
