language: node_js
os: linux
node_js:
- '10'
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  cleanup: false
  on:
    branch: master
    tags: true
    repo: bisand/tibber-api
  tag: next
