import { IAddress } from './IAddress';
import { IMeteringPointData } from './IMeteringPointData';
import { IHomeFeatures } from "./IHomeFeatures";
import { ILegalEntity } from './ILegalEntity';
import { ISubscription } from './ISubscription';
import { HomeAvatar } from './enums/HomeAvatar';
import { HomeType } from './enums/HomeType';
import { HeatingSource } from './enums/HeatingSource';
import { IHomeConsumptionConnection } from './IHomeConsumptionConnection';
import { IHomeProductionConnection } from './IHomeProductionConnection';
export interface IHome {
    id: string;
    timeZone: string;
    appNickname: string;
    appAvatar: HomeAvatar;
    size: number;
    type: HomeType;
    numberOfResidents: number;
    primaryHeatingSource: HeatingSource;
    hasVentilationSystem: boolean;
    mainFuseSize: number;
    address: IAddress;
    owner: ILegalEntity;
    consumption: IHomeConsumptionConnection;
    meteringPointData: IMeteringPointData;
    currentSubscription: ISubscription;
    subscriptions: ISubscription[];
    production: IHomeProductionConnection;
    features: IHomeFeatures;
}
