export enum AppScreen {
    HOME = 'HOME',
    REPORTS = 'REPORTS',
    CONSUMPTION = 'CONSUMPTION',
    COMPARISON = 'COMPARISON',
    DISAGGREGATION = 'DISAGGREGATION',
    HOME_PROFILE = 'HOME_PROFILE',
    CUSTOMER_PROFILE = 'CUSTOMER_PROFILE',
    METER_READING = 'METER_READING',
    NOTIFICATIONS = 'NOTIFICATIONS',
    INVOICES = 'INVOICES',
}