export enum HeatingSource {
    AIR2AIR_HEATPUMP = 'AIR2AIR_HEATPUMP',
    ELECTRICITY = 'ELECTRICITY',
    GROUND = 'GROUND',
    DISTRICT_HEATING = 'DISTRICT_HEATING',
    ELECTRIC_BOILER = 'ELECTRIC_BOILER',
    AIR2WATER_HEATPUMP = 'AIR2WATER_HEATPUMP',
    OTHER = 'OTHER',
}