export enum HomeAvatar {
    APARTMENT = 'APARTMENT',
    ROWHOUSE = 'ROWHOUSE',
    FLOORHOUSE1 = 'FLOORHOUSE1',
    FLOORHOUSE2 = 'FLOORHOUSE2',
    FLOORHOUSE3 = 'FLOORHOUSE3',
    COTTAGE = 'COTTAGE',
    CASTLE = 'CASTLE',
}